
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'



import Header from '@/components/header/Header'
import TopHeader from '@/components/header/TopHeader'
import Footer from '@/components/Footer/Footer'
import Providers from '@/components/Provider/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
 
  return (
   <Providers>
     <html lang="en">
      
      <body className={inter.className}>
        <TopHeader></TopHeader>
      <Header></Header>
        {children}
        <Footer></Footer>
        </body>
    </html>
   </Providers>
  )   
}
